services:
  digital_ustad_academy:
    container_name: digital_ustad_academy_api
    build:
      context: .
      target: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.digitalustad.rule=Host(`api.digitalustadacademy.com`)" # replace the api.localhost with my domain name 'api.digitalustadacaedmy.com' , the HostRegexp(`{any:.*}`) for running ngrok app
      - "traefik.http.services.digitalustad.loadbalancer.server.port=5000"
      - "traefik.http.routers.digitalustad.entrypoints=websecure"
      - "traefik.http.routers.digitalustad.tls=true"
      - "traefik.http.routers.digitalustad.tls.certresolver=letsencrypt" # for testing ssl in local type `selfsigned`  or `letsencrypt`
    networks:
      - traefik-network
    depends_on:
      - mongo 
    env_file:
      - ./.env

  traefik:
    image: traefik:v3.6
    container_name: traefik-app
    command:
      - "--providers.docker=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=contact@digitalustadacademy.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # selef certificate
      # - "--certificatesresolvers.selfsigned.acme.tlschallenge=true"
      # - "--certificatesresolvers.selfsigned.acme.email=you@example.com"
      # - "--certificatesresolvers.selfsigned.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/traefik/letsencrypt:/letsencrypt
    networks:
      - traefik-network      
      
  mongo:
    image: mongo
    restart: always
    networks:
      - traefik-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./mongo-data:/data/db  

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - traefik-network
    ports:
      - 8082:8081  
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

networks:
  traefik-network:
    external: true
         